//go:generate go run .

// Package main implements the OpenAPI codegen tool that generates structural
// validation metadata from vendored k8s OpenAPI v3 schemas.
package main

import (
	"embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

//go:embed schemas/*.json
var schemaFS embed.FS

// OpenAPISchema represents the structure of an OpenAPI v3 schema file.
type OpenAPISchema struct {
	Type        string                 `json:"type,omitempty"`
	Format      string                 `json:"format,omitempty"`
	Description string                 `json:"description,omitempty"`
	Properties  map[string]*OpenAPISchema `json:"properties,omitempty"`
	Items       *OpenAPISchema         `json:"items,omitempty"`
	Required    []string               `json:"required,omitempty"`
	Enum        []any                  `json:"enum,omitempty"`
	Minimum     *float64               `json:"minimum,omitempty"`
	Maximum     *float64               `json:"maximum,omitempty"`
}

// FieldMetadata encodes a single field's structural validation rules from the k8s OpenAPI schema.
type FieldMetadata struct {
	Path       string
	Type       string
	Format     string
	Required   bool
	EnumValues []string
	RangeMin   *float64
	RangeMax   *float64
}

// SchemaMetadata holds all field metadata for a given struct type.
type SchemaMetadata map[string]FieldMetadata

func main() {
	if len(os.Args) > 1 && os.Args[1] == "--help" {
		fmt.Println("usage: go run .")
		fmt.Println("Generates pkg/validator/generated_structural.go from vendored k8s OpenAPI schemas.")
		os.Exit(0)
	}

	schemas := listSchemas()
	if len(schemas) == 0 {
		fmt.Fprintln(os.Stderr, "no schemas found")
		os.Exit(1)
	}

	output := generateOutput(schemas)

	outPath := filepath.Join("..", "..", "pkg", "validator", "generated_structural.go")
	if err := os.WriteFile(outPath, []byte(output), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", outPath, err)
		os.Exit(1)
	}

	fmt.Printf("generated %s\n", outPath)
}

func listSchemas() []string {
	entries, err := schemaFS.ReadDir("schemas")
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read schemas dir: %v\n", err)
		os.Exit(1)
	}
	var schemas []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".json") {
			schemas = append(schemas, e.Name())
		}
	}
	sort.Strings(schemas)
	return schemas
}

func generateOutput(schemas []string) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by tools/codegen; DO NOT EDIT.\n")
	sb.WriteString("//go:generate go run ../../tools/codegen\n\n")
	sb.WriteString("package validator\n\n")
	sb.WriteString("import \"sync\"\n\n")

	// Build all SchemaMetadata keyed by type name
	allMetadata := make(map[string]SchemaMetadata)
	for _, schemaName := range schemas {
		typeName := strings.TrimSuffix(schemaName, ".json")
		schema, err := loadSchema(schemaName)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to load schema %s: %v\n", schemaName, err)
			os.Exit(1)
		}
		metadata := extractMetadata(typeName, schema, "")
		sorted := sortMetadata(metadata)
		allMetadata[typeName] = sorted
	}

	// Write type definitions
	sb.WriteString("// FieldMetadata encodes a single field's structural validation rules from the k8s OpenAPI schema.\n")
	sb.WriteString("type FieldMetadata struct {\n")
	sb.WriteString("\tPath       string\n")
	sb.WriteString("\tType       string\n")
	sb.WriteString("\tFormat     string\n")
	sb.WriteString("\tRequired   bool\n")
	sb.WriteString("\tEnumValues []string\n")
	sb.WriteString("\tRangeMin   *float64\n")
	sb.WriteString("\tRangeMax   *float64\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// SchemaMetadata holds all field metadata for a given struct type.\n")
	sb.WriteString("type SchemaMetadata map[string]FieldMetadata\n\n")

	// Collect all paths for the flat index (deduplicated)
	allPaths := make(map[string]FieldMetadata) // path -> first metadata seen
	for _, typeName := range sortedTypes(allMetadata) {
		metadata := allMetadata[typeName]
		for path, meta := range metadata {
			if _, exists := allPaths[path]; !exists {
				allPaths[path] = meta
			}
		}
	}

	// Write var declarations (sorted for determinism)
	typeNames := sortedTypes(allMetadata)
	for _, typeName := range typeNames {
		upperName := toUpperName(typeName)
		sb.WriteString(fmt.Sprintf("// %s contains structural metadata for %s.\n", upperName, typeName))
		sb.WriteString(fmt.Sprintf("var %s SchemaMetadata\n\n", upperName))
	}

	// Write init function that populates both the flat index AND the per-schema vars
	sb.WriteString("var (\n")
	sb.WriteString("\tstructuralIndex map[string]FieldMetadata\n")
	sb.WriteString("\tstructuralOnce  sync.Once\n")
	sb.WriteString(")\n\n")
	sb.WriteString("func init() {\n")
	sb.WriteString("\tstructuralOnce.Do(func() {\n")
	sb.WriteString("\t\tstructuralIndex = make(map[string]FieldMetadata)\n")

	// Collect entries sorted by path for determinism
	type initEntry struct {
		path string
		meta FieldMetadata
	}
	var allEntries []initEntry
	for path := range allPaths {
		allEntries = append(allEntries, initEntry{path: path, meta: allPaths[path]})
	}
	sort.Slice(allEntries, func(i, j int) bool {
		return allEntries[i].path < allEntries[j].path
	})

	for _, e := range allEntries {
		m := e.meta
		fmt.Fprintf(&sb, "\t\tstructuralIndex[%q] = FieldMetadata{Path:%q,Type:%q,Format:%q,Required:%v", e.path, e.path, m.Type, m.Format, m.Required)
		if len(m.EnumValues) > 0 {
			fmt.Fprintf(&sb, ",EnumValues:%v", quotedSlice(m.EnumValues))
		}
		if m.RangeMin != nil {
			fmt.Fprintf(&sb, ",RangeMin:%v", floatPtrStr(*m.RangeMin))
		}
		if m.RangeMax != nil {
			fmt.Fprintf(&sb, ",RangeMax:%v", floatPtrStr(*m.RangeMax))
		}
		sb.WriteString("}\n")
	}

	// Initialize per-schema variables
	for _, typeName := range typeNames {
		upperName := toUpperName(typeName)
		metadata := allMetadata[typeName]
		if len(metadata) == 0 {
			continue
		}
		sb.WriteString(fmt.Sprintf("\t\t%s = SchemaMetadata{\n", upperName))
		// Sort entries by path
		entries := make([]initEntry, 0, len(metadata))
		for path, meta := range metadata {
			entries = append(entries, initEntry{path: path, meta: meta})
		}
		sort.Slice(entries, func(i, j int) bool {
			return entries[i].path < entries[j].path
		})
		for _, e := range entries {
			m := e.meta
			fmt.Fprintf(&sb, "\t\t\t%q: FieldMetadata{Path:%q,Type:%q,Format:%q,Required:%v", e.path, e.path, m.Type, m.Format, m.Required)
			if len(m.EnumValues) > 0 {
				fmt.Fprintf(&sb, ",EnumValues:%v", quotedSlice(m.EnumValues))
			}
			if m.RangeMin != nil {
				fmt.Fprintf(&sb, ",RangeMin:%v", floatPtrStr(*m.RangeMin))
			}
			if m.RangeMax != nil {
				fmt.Fprintf(&sb, ",RangeMax:%v", floatPtrStr(*m.RangeMax))
			}
			sb.WriteString("},\n")
		}
		sb.WriteString("\t\t}\n")
	}

	sb.WriteString("\t})\n")
	sb.WriteString("}\n\n")

	// Write LookupStructural function
	sb.WriteString("// LookupStructural returns the FieldMetadata for a given path, or false if not found.\n")
	sb.WriteString("func LookupStructural(path string) (FieldMetadata, bool) {\n")
	sb.WriteString("\tm, ok := structuralIndex[path]\n")
	sb.WriteString("\treturn m, ok\n")
	sb.WriteString("}\n\n")

	// Write GetAllSchemas function (for testing)
	sb.WriteString("// GetAllSchemas returns all registered schema metadata (for testing).\n")
	sb.WriteString("func GetAllSchemas() map[string]SchemaMetadata {\n")
	sb.WriteString("\treturn map[string]SchemaMetadata{\n")
	for _, typeName := range typeNames {
		upperName := toUpperName(typeName)
		fmt.Fprintf(&sb, "\t\t%q: %s,\n", typeName, upperName)
	}
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")

	return sb.String()
}

func sortedTypes(m map[string]SchemaMetadata) []string {
	typeNames := make([]string, 0, len(m))
	for tn := range m {
		typeNames = append(typeNames, tn)
	}
	sort.Strings(typeNames)
	return typeNames
}

func loadSchema(name string) (*OpenAPISchema, error) {
	data, err := schemaFS.ReadFile(filepath.Join("schemas", name))
	if err != nil {
		return nil, err
	}
	var schema OpenAPISchema
	if err := json.Unmarshal(data, &schema); err != nil {
		return nil, err
	}
	return &schema, nil
}

func extractMetadata(typeName string, schema *OpenAPISchema, prefix string) SchemaMetadata {
	metadata := make(SchemaMetadata)
	if schema == nil {
		return metadata
	}

	if schema.Properties == nil {
		return metadata
	}

	requiredSet := make(map[string]bool)
	for _, req := range schema.Required {
		requiredSet[req] = true
	}

	extractFields(typeName, schema.Properties, prefix, requiredSet, metadata)

	return metadata
}

func extractFields(typeName string, properties map[string]*OpenAPISchema, prefix string, requiredSet map[string]bool, metadata SchemaMetadata) {
	for propName, propSchema := range properties {
		path := propName
		if prefix != "" {
			path = prefix + "." + propName
		}

		fieldType := propSchema.Type
		if fieldType == "" && propSchema.Properties != nil {
			fieldType = "object"
		}

		field := FieldMetadata{
			Path:     path,
			Type:     fieldType,
			Format:   propSchema.Format,
			Required: requiredSet[propName],
		}

		// Handle enum values
		if len(propSchema.Enum) > 0 {
			field.EnumValues = make([]string, 0, len(propSchema.Enum))
			for _, v := range propSchema.Enum {
				if s, ok := v.(string); ok {
					field.EnumValues = append(field.EnumValues, s)
				}
			}
			sort.Strings(field.EnumValues)
		}

		// Handle range constraints
		if propSchema.Minimum != nil {
			min := *propSchema.Minimum
			field.RangeMin = &min
		}
		if propSchema.Maximum != nil {
			max := *propSchema.Maximum
			field.RangeMax = &max
		}

		metadata[path] = field

		// Recurse into nested objects
		if fieldType == "object" && propSchema.Properties != nil {
			extractFields(typeName, propSchema.Properties, path, requiredSet, metadata)
		}

		// Handle array items - recurse into items' properties
		if propType := propSchema.Type; propType == "array" && propSchema.Items != nil {
			if propSchema.Items.Properties != nil {
				nestedPrefix := path + "[*]"
				extractFields(typeName, propSchema.Items.Properties, nestedPrefix, requiredSet, metadata)
			}
		}
	}
}

func sortMetadata(m SchemaMetadata) SchemaMetadata {
	paths := make([]string, 0, len(m))
	for p := range m {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	sorted := make(SchemaMetadata, len(m))
	for _, p := range paths {
		sorted[p] = m[p]
	}
	return sorted
}

func toUpperName(typeName string) string {
	// io.k8s.api.core.v1.PodSpec -> PodSpec
	parts := strings.Split(typeName, ".")
	return parts[len(parts)-1]
}

func quotedSlice(ss []string) string {
	if len(ss) == 0 {
		return "nil"
	}
	var sb strings.Builder
	sb.WriteString("[]string{")
	for i, s := range ss {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(fmt.Sprintf("%q", s))
	}
	sb.WriteString("}")
	return sb.String()
}

func floatPtrStr(f float64) string {
	return fmt.Sprintf("func() *float64 { v := %v; return &v }()", f)
}