//go:generate go run .

// Package main implements the OpenAPI codegen tool that generates structural
// validation metadata from vendored k8s OpenAPI v3 schemas.
package main

import (
	"embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

//go:embed schemas/*.json
var schemaFS embed.FS

// OpenAPISchema represents the structure of an OpenAPI v3 schema file.
type OpenAPISchema struct {
	Ref         string                    `json:"$ref,omitempty"`
	Type        string                    `json:"type,omitempty"`
	Format      string                    `json:"format,omitempty"`
	Description string                    `json:"description,omitempty"`
	Properties  map[string]*OpenAPISchema `json:"properties,omitempty"`
	Items       *OpenAPISchema            `json:"items,omitempty"`
	Required    []string                  `json:"required,omitempty"`
	Enum        []any                     `json:"enum,omitempty"`
	Minimum     *float64                  `json:"minimum,omitempty"`
	Maximum     *float64                  `json:"maximum,omitempty"`
	MinLength   *int                      `json:"minLength,omitempty"`
	MaxLength   *int                      `json:"maxLength,omitempty"`
}

// FieldMetadata encodes a single field's structural validation rules from the k8s OpenAPI schema.
type FieldMetadata struct {
	Path       string   `json:"path" yaml:"path"`
	Type       string   `json:"type" yaml:"type"`
	Format     string   `json:"format,omitempty" yaml:"format,omitempty"`
	Required   bool     `json:"required" yaml:"required"`
	EnumValues []string `json:"enumValues,omitempty" yaml:"enumValues,omitempty"`
	MinValue   *float64 `json:"minValue,omitempty" yaml:"minValue,omitempty"`
	MaxValue   *float64 `json:"maxValue,omitempty" yaml:"maxValue,omitempty"`
	MinLength  *int     `json:"minLength,omitempty" yaml:"minLength,omitempty"`
	MaxLength  *int     `json:"maxLength,omitempty" yaml:"maxLength,omitempty"`
}

// SchemaMetadata holds all field metadata for a given struct type.
type SchemaMetadata map[string]FieldMetadata

func main() {
	if len(os.Args) > 1 && os.Args[1] == "--help" {
		fmt.Println("usage: go run .")
		fmt.Println("Generates pkg/validator/generated_structural.go from vendored k8s OpenAPI schemas.")
		os.Exit(0)
	}

	schemas := listSchemas()
	if len(schemas) == 0 {
		fmt.Fprintln(os.Stderr, "no schemas found")
		os.Exit(1)
	}

	output := generateOutput(schemas)

	outPath := filepath.Join("..", "..", "pkg", "validator", "generated_structural.go")
	if err := os.WriteFile(outPath, []byte(output), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", outPath, err)
		os.Exit(1)
	}

	fmt.Printf("generated %s\n", outPath)
}

func listSchemas() []string {
	entries, err := schemaFS.ReadDir("schemas")
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read schemas dir: %v\n", err)
		os.Exit(1)
	}
	var schemas []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".json") {
			schemas = append(schemas, e.Name())
		}
	}
	sort.Strings(schemas)
	return schemas
}

func generateOutput(schemas []string) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by tools/codegen; DO NOT EDIT.\n")
	sb.WriteString("//go:generate go run ../../tools/codegen\n\n")
	sb.WriteString("package validator\n\n")
	sb.WriteString("import \"sync\"\n\n")

	// Build all SchemaMetadata keyed by type name
	allMetadata := make(map[string]SchemaMetadata)
	for _, schemaName := range schemas {
		typeName := strings.TrimSuffix(schemaName, ".json")
		schema, err := loadSchema(schemaName)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to load schema %s: %v\n", schemaName, err)
			os.Exit(1)
		}
		metadata := extractMetadata(typeName, schema, "")
		sorted := sortMetadata(metadata)
		allMetadata[typeName] = sorted
	}

	// Write type definitions
	sb.WriteString("// FieldMetadata encodes a single field's structural validation rules from the k8s OpenAPI schema.\n")
	sb.WriteString("type FieldMetadata struct {\n")
	sb.WriteString("\tPath       string   `json:\"path\" yaml:\"path\"`\n")
	sb.WriteString("\tType       string   `json:\"type\" yaml:\"type\"`\n")
	sb.WriteString("\tFormat     string   `json:\"format,omitempty\" yaml:\"format,omitempty\"`\n")
	sb.WriteString("\tRequired   bool     `json:\"required\" yaml:\"required\"`\n")
	sb.WriteString("\tEnumValues []string `json:\"enumValues,omitempty\" yaml:\"enumValues,omitempty\"`\n")
	sb.WriteString("\tMinValue   *float64 `json:\"minValue,omitempty\" yaml:\"minValue,omitempty\"`\n")
	sb.WriteString("\tMaxValue   *float64 `json:\"maxValue,omitempty\" yaml:\"maxValue,omitempty\"`\n")
	sb.WriteString("\tMinLength  *int     `json:\"minLength,omitempty\" yaml:\"minLength,omitempty\"`\n")
	sb.WriteString("\tMaxLength  *int     `json:\"maxLength,omitempty\" yaml:\"maxLength,omitempty\"`\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// SchemaMetadata holds all field metadata for a given struct type.\n")
	sb.WriteString("type SchemaMetadata map[string]FieldMetadata\n\n")

	// Collect all paths for the flat index (deduplicated)
	allPaths := make(map[string]FieldMetadata) // path -> first metadata seen
	for _, typeName := range sortedTypes(allMetadata) {
		metadata := allMetadata[typeName]
		// Sort keys for deterministic iteration (Go map iteration is randomized)
		paths := make([]string, 0, len(metadata))
		for p := range metadata {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, path := range paths {
			meta := metadata[path]
			if _, exists := allPaths[path]; !exists {
				allPaths[path] = meta
			}
		}
	}

	// Write var declarations (sorted for determinism)
	typeNames := sortedTypes(allMetadata)
	for _, typeName := range typeNames {
		upperName := toUpperName(typeName)
		sb.WriteString(fmt.Sprintf("// %sDeferredFields contains structural metadata for %s.\n", upperName, typeName))
		sb.WriteString(fmt.Sprintf("var %sDeferredFields SchemaMetadata\n\n", upperName))
	}

	// Write init function that populates both the flat index AND the per-schema vars
	sb.WriteString("var (\n")
	sb.WriteString("\tdeferredFieldIndex map[string]FieldMetadata\n")
	sb.WriteString("\tdeferredFieldInit  sync.Once\n")
	sb.WriteString(")\n\n")
	sb.WriteString("func init() {\n")
	sb.WriteString("\tdeferredFieldInit.Do(func() {\n")
	sb.WriteString("\t\tdeferredFieldIndex = make(map[string]FieldMetadata)\n")

	// Collect entries sorted by path for determinism
	type initEntry struct {
		path string
		meta FieldMetadata
	}
	var allEntries []initEntry
	for path := range allPaths {
		allEntries = append(allEntries, initEntry{path: path, meta: allPaths[path]})
	}
	sort.Slice(allEntries, func(i, j int) bool {
		return allEntries[i].path < allEntries[j].path
	})

	for _, e := range allEntries {
		m := e.meta
		fmt.Fprintf(&sb, "\t\tdeferredFieldIndex[%q] = FieldMetadata{Path:%q,Type:%q,Format:%q,Required:%v", e.path, e.path, m.Type, m.Format, m.Required)
		if len(m.EnumValues) > 0 {
			fmt.Fprintf(&sb, ",EnumValues:%v", quotedSlice(m.EnumValues))
		}
		if m.MinValue != nil {
			fmt.Fprintf(&sb, ",MinValue:%v", floatPtrStr(*m.MinValue))
		}
		if m.MaxValue != nil {
			fmt.Fprintf(&sb, ",MaxValue:%v", floatPtrStr(*m.MaxValue))
		}
		if m.MinLength != nil {
			fmt.Fprintf(&sb, ",MinLength:%v", intPtrStr(*m.MinLength))
		}
		if m.MaxLength != nil {
			fmt.Fprintf(&sb, ",MaxLength:%v", intPtrStr(*m.MaxLength))
		}
		sb.WriteString("}\n")
	}

	// Initialize per-schema variables
	for _, typeName := range typeNames {
		upperName := toUpperName(typeName)
		metadata := allMetadata[typeName]
		if len(metadata) == 0 {
			continue
		}
		sb.WriteString(fmt.Sprintf("\t\t%sDeferredFields = SchemaMetadata{\n", upperName))
		// Sort entries by path
		entries := make([]initEntry, 0, len(metadata))
		for path, meta := range metadata {
			entries = append(entries, initEntry{path: path, meta: meta})
		}
		sort.Slice(entries, func(i, j int) bool {
			return entries[i].path < entries[j].path
		})
		for _, e := range entries {
			m := e.meta
			fmt.Fprintf(&sb, "\t\t\t%q: FieldMetadata{Path:%q,Type:%q,Format:%q,Required:%v", e.path, e.path, m.Type, m.Format, m.Required)
			if len(m.EnumValues) > 0 {
				fmt.Fprintf(&sb, ",EnumValues:%v", quotedSlice(m.EnumValues))
			}
			if m.MinValue != nil {
				fmt.Fprintf(&sb, ",MinValue:%v", floatPtrStr(*m.MinValue))
			}
			if m.MaxValue != nil {
				fmt.Fprintf(&sb, ",MaxValue:%v", floatPtrStr(*m.MaxValue))
			}
			if m.MinLength != nil {
				fmt.Fprintf(&sb, ",MinLength:%v", intPtrStr(*m.MinLength))
			}
			if m.MaxLength != nil {
				fmt.Fprintf(&sb, ",MaxLength:%v", intPtrStr(*m.MaxLength))
			}
			sb.WriteString("},\n")
		}
		sb.WriteString("\t\t}\n")
	}

	sb.WriteString("\t})\n")
	sb.WriteString("}\n\n")

	// Write LookupDeferredField function
	sb.WriteString("// LookupDeferredField returns the FieldMetadata for a given path, or false if not found.\n")
	sb.WriteString("func LookupDeferredField(path string) (FieldMetadata, bool) {\n")
	sb.WriteString("\tm, ok := deferredFieldIndex[path]\n")
	sb.WriteString("\treturn m, ok\n")
	sb.WriteString("}\n\n")

	// Write GetAllSchemas function (for testing)
	sb.WriteString("// GetAllSchemas returns all registered schema metadata (for testing).\n")
	sb.WriteString("func GetAllSchemas() map[string]SchemaMetadata {\n")
	sb.WriteString("\treturn map[string]SchemaMetadata{\n")
	for _, typeName := range typeNames {
		upperName := toUpperName(typeName)
		fmt.Fprintf(&sb, "\t\t%q: %sDeferredFields,\n", typeName, upperName)
	}
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")

	return sb.String()
}

func sortedTypes(m map[string]SchemaMetadata) []string {
	typeNames := make([]string, 0, len(m))
	for tn := range m {
		typeNames = append(typeNames, tn)
	}
	sort.Strings(typeNames)
	return typeNames
}

func loadSchema(name string) (*OpenAPISchema, error) {
	data, err := schemaFS.ReadFile(filepath.Join("schemas", name))
	if err != nil {
		return nil, err
	}
	var schema OpenAPISchema
	if err := json.Unmarshal(data, &schema); err != nil {
		return nil, err
	}
	return &schema, nil
}

func extractMetadata(typeName string, schema *OpenAPISchema, prefix string) SchemaMetadata {
	metadata := make(SchemaMetadata)
	if schema == nil {
		return metadata
	}

	if schema.Properties == nil {
		return metadata
	}

	requiredSet := make(map[string]bool)
	for _, req := range schema.Required {
		requiredSet[req] = true
	}

	processing := make(map[string]bool)
	finished := make(map[string]bool)
	extractFields(typeName, schema.Properties, prefix, requiredSet, metadata, processing, finished)

	return metadata
}

// loadSchema loads a schema from the embedded fs by type name.
// The typeName is expected to be in the format "io.k8s.api.core.v1.TypeName".
func loadSchemaFromName(typeName string) (*OpenAPISchema, string, error) {
	fileName := typeName + ".json"
	schema, err := loadSchema(fileName)
	if err != nil {
		return nil, "", err
	}
	return schema, typeName, nil
}

func extractFields(typeName string, properties map[string]*OpenAPISchema, prefix string, requiredSet map[string]bool, metadata SchemaMetadata, processing, finished map[string]bool) {
	// Cycle detection
	if finished[typeName] {
		return
	}
	if processing[typeName] {
		return
	}
	processing[typeName] = true
	defer func() {
		processing[typeName] = false
		finished[typeName] = true
	}()

	for propName, propSchema := range properties {
		// Issue 1 fix: construct full JSON paths from schema root.
		// Prefix starts as "." (the type root), so first-level fields get paths like ".name".
		// Nested object fields get paths like ".affinity.podAffinity".
		// Array item fields get paths like ".containers[*].name".
		path := "." + propName
		if prefix != "" {
			path = prefix + "." + propName
		}

		fieldType := propSchema.Type
		if fieldType == "" && propSchema.Properties != nil {
			fieldType = "object"
		}

		field := FieldMetadata{
			Path:     path,
			Type:     fieldType,
			Format:   propSchema.Format,
			Required: requiredSet[propName],
		}

		// Handle enum values
		if len(propSchema.Enum) > 0 {
			field.EnumValues = make([]string, 0, len(propSchema.Enum))
			for _, v := range propSchema.Enum {
				if s, ok := v.(string); ok {
					field.EnumValues = append(field.EnumValues, s)
				}
			}
			sort.Strings(field.EnumValues)
		}

		// Handle minLength/maxLength constraints
		if propSchema.MinLength != nil {
			minLen := *propSchema.MinLength
			field.MinLength = &minLen
		}
		if propSchema.MaxLength != nil {
			maxLen := *propSchema.MaxLength
			field.MaxLength = &maxLen
		}

		// Handle range constraints
		if propSchema.Minimum != nil {
			min := *propSchema.Minimum
			field.MinValue = &min
		}
		if propSchema.Maximum != nil {
			max := *propSchema.Maximum
			field.MaxValue = &max
		}

		metadata[path] = field

		// Recurse into nested objects
		if fieldType == "object" && propSchema.Properties != nil {
			extractFields(typeName, propSchema.Properties, path, requiredSet, metadata, processing, finished)
		}

		// Handle array items - recurse into items' properties
		if propType := propSchema.Type; propType == "array" && propSchema.Items != nil {
			if propSchema.Items.Properties != nil {
				nestedPrefix := path + "[*]"
				extractFields(typeName, propSchema.Items.Properties, nestedPrefix, requiredSet, metadata, processing, finished)
			} else if propSchema.Items.Ref != "" {
				// Items has a $ref but no direct Properties.
				// Resolve the reference and extract its properties.
				refTypeName := strings.TrimPrefix(propSchema.Items.Ref, "#/components/schemas/")
				if refTypeName != propSchema.Items.Ref {
					refSchema, _, err := loadSchemaFromName(refTypeName)
					if err == nil && refSchema.Properties != nil {
						refRequired := make(map[string]bool)
						for _, req := range refSchema.Required {
							refRequired[req] = true
						}
						nestedPrefix := path + "[*]"
						refProcessing := make(map[string]bool)
						refFinished := make(map[string]bool)
						extractFields(refTypeName, refSchema.Properties, nestedPrefix, refRequired, metadata, refProcessing, refFinished)
					}
				}
			}
		}

		// Resolve $ref by loading the referenced schema and recursing.
		// Use fresh cycle-detection maps so the same referenced type can be
		// extracted under multiple field prefixes (e.g. livenessProbe, readinessProbe,
		// and startupProbe all $ref Probe).
		if propSchema.Ref != "" {
			refTypeName := strings.TrimPrefix(propSchema.Ref, "#/components/schemas/")
			if refTypeName != propSchema.Ref {
				refSchema, _, err := loadSchemaFromName(refTypeName)
				if err == nil && refSchema.Properties != nil {
					refRequired := make(map[string]bool)
					for _, req := range refSchema.Required {
						refRequired[req] = true
					}
					refProcessing := make(map[string]bool)
					refFinished := make(map[string]bool)
					extractFields(refTypeName, refSchema.Properties, path, refRequired, metadata, refProcessing, refFinished)
				}
			}
		}

		// Handle bare references: a property with no type, no $ref, no nested properties,
		// but whose name matches a schema file that IS a defined type. This catches
		// union-field references like LifecycleHandler.exec → ExecAction where the
		// schema has no $ref but the field name is the referenced type in disguise.
		if propSchema.Type == "" && propSchema.Ref == "" && len(propSchema.Properties) == 0 && propSchema.Items == nil {
			var candidateType string
			var refSchema *OpenAPISchema

			// Direct mapping for known lifecycle handler fields.
			// Lifecycle.postStart and Lifecycle.preStop are inline objects whose type is
			// LifecycleHandler (not named PostStart/PreStop by convention).
			if propName == "postStart" || propName == "preStop" {
				if s, _, err := loadSchemaFromName("io.k8s.api.core.v1.LifecycleHandler"); err == nil && s.Properties != nil {
					candidateType, refSchema = "io.k8s.api.core.v1.LifecycleHandler", s
				}
			}

			// Direct mapping for LifecycleHandler action sub-fields.
			// Strategy 2 capitalizes "tcpSocket" -> "TcpSocketAction" (wrong case),
			// so we handle these known mappings explicitly.
			switch propName {
			case "tcpSocket":
				if s, _, err := loadSchemaFromName("io.k8s.api.core.v1.TCPSocketAction"); err == nil && s.Properties != nil {
					candidateType, refSchema = "io.k8s.api.core.v1.TCPSocketAction", s
				}
			case "httpGet":
				if s, _, err := loadSchemaFromName("io.k8s.api.core.v1.HTTPGetAction"); err == nil && s.Properties != nil {
					candidateType, refSchema = "io.k8s.api.core.v1.HTTPGetAction", s
				}
			case "exec":
				if s, _, err := loadSchemaFromName("io.k8s.api.core.v1.ExecAction"); err == nil && s.Properties != nil {
					candidateType, refSchema = "io.k8s.api.core.v1.ExecAction", s
				}
			case "secretKeyRef":
				if s, _, err := loadSchemaFromName("io.k8s.api.core.v1.SecretKeySelector"); err == nil && s.Properties != nil {
					candidateType, refSchema = "io.k8s.api.core.v1.SecretKeySelector", s
				}
			case "configMapKeyRef":
				if s, _, err := loadSchemaFromName("io.k8s.api.core.v1.ConfigMapKeySelector"); err == nil && s.Properties != nil {
					candidateType, refSchema = "io.k8s.api.core.v1.ConfigMapKeySelector", s
				}
			}

			// Strategy 1: Capitalized property name (e.g. "exec" -> "Exec")
			capitalized := strings.ToUpper(propName[:1]) + propName[1:]
			tentative := "io.k8s.api.core.v1." + capitalized
			if s, _, err := loadSchemaFromName(tentative); err == nil && s.Properties != nil {
				candidateType, refSchema = tentative, s
			}

			// Strategy 2: Property name + "Action" suffix (e.g. "exec" -> "ExecAction")
			if refSchema == nil {
				tentative = "io.k8s.api.core.v1." + capitalized + "Action"
				if s, _, err := loadSchemaFromName(tentative); err == nil && s.Properties != nil {
					candidateType, refSchema = tentative, s
				}
			}

			// Strategy 3: Case-insensitive scan (e.g. "httpGet" matches "HTTPGetAction")
			if refSchema == nil {
				entries, _ := schemaFS.ReadDir("schemas")
				for _, e := range entries {
					if e.IsDir() {
						continue
					}
					baseName := strings.TrimSuffix(e.Name(), ".json")
					if strings.HasPrefix(strings.ToLower(baseName), strings.ToLower(propName)) {
						tentative = "io.k8s.api.core.v1." + baseName
						if s, _, err := loadSchemaFromName(tentative); err == nil && s.Properties != nil {
							candidateType, refSchema = tentative, s
							break
						}
					}
				}
			}


			// Strategy 4: Property name is a case-insensitive substring of the type name.
			// This handles tcpsocket -> TCPSocketAction and httpGet -> HTTPGetAction
			// where the type name contains the lowercased property name.
			if refSchema == nil {
				entries, _ := schemaFS.ReadDir("schemas")
				for _, e := range entries {
					if e.IsDir() {
						continue
					}
					baseName := strings.TrimSuffix(e.Name(), ".json")
					candidateTypeName := strings.TrimPrefix(baseName, "io.k8s.api.core.v1.")
					// Check if the lowercased property name appears in the type name
					lowerProp := strings.ToLower(propName)
					lowerCandidate := strings.ToLower(candidateTypeName)
					if strings.Contains(lowerCandidate, lowerProp) {
						tentative := "io.k8s.api.core.v1." + baseName
						if s, _, err := loadSchemaFromName(tentative); err == nil && s.Properties != nil {
							candidateType, refSchema = tentative, s
							break
						}
					}
				}
			}

						// If we found a matching schema, extract its fields into the current path
			if refSchema != nil {
				refRequired := make(map[string]bool)
				for _, req := range refSchema.Required {
					refRequired[req] = true
				}
				refProcessing := make(map[string]bool)
				refFinished := make(map[string]bool)
				extractFields(candidateType, refSchema.Properties, path, refRequired, metadata, refProcessing, refFinished)
			}
		}
	}
}

func sortMetadata(m SchemaMetadata) SchemaMetadata {
	paths := make([]string, 0, len(m))
	for p := range m {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	sorted := make(SchemaMetadata, len(m))
	for _, p := range paths {
		sorted[p] = m[p]
	}
	return sorted
}

func toUpperName(typeName string) string {
	// io.k8s.api.core.v1.PodSpec -> PodSpec
	parts := strings.Split(typeName, ".")
	return parts[len(parts)-1]
}

func quotedSlice(ss []string) string {
	if len(ss) == 0 {
		return "nil"
	}
	var sb strings.Builder
	sb.WriteString("[]string{")
	for i, s := range ss {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(fmt.Sprintf("%q", s))
	}
	sb.WriteString("}")
	return sb.String()
}

func floatPtrStr(f float64) string {
	return fmt.Sprintf("func() *float64 { v := %v; return &v }()", f)
}

func intPtrStr(i int) string {
	return fmt.Sprintf("func() *int { v := %v; return &v }()", i)
}