package validator

import (
	"fmt"
	"reflect"
	"regexp"
	"strings"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/validation/field"
)

// deferredFieldIndex is the pre-compiled metadata index (generated by codegen).
// deferredFieldInit ensures thread-safe lazy compilation of the index.

// normalizePath strips numeric array indices from a field.Path string for
// index-independent lookup in deferredFieldIndex (which uses keys like .containers[*]
// not .containers[0]).
// Example: ".spec.template.spec.topologySpreadConstraints[0].topologyKey"
//  -> ".topologyKey"
// normalizePath strips array indices and parent path segments from a field.Path,
// returning the last field name prefixed with "." for index lookup.
// field.Path.String() uses bracket notation like [spec][template][spec][topologyKey][0][topologyKey].
// We convert this to just ".topologyKey" to match the deferredFieldIndex keys.
func normalizePath(p *field.Path) string {
	s := p.String()
	// Strip array indices: [0], [1], etc.
	re := regexp.MustCompile(`\[\d+\]`)
	s = re.ReplaceAllString(s, "")

	// Extract the last bracket-delimited segment: [name]
	// e.g. [spec][template][spec][topologyKey] -> topologyKey
	if idx := strings.LastIndex(s, "["); idx >= 0 {
		end := strings.LastIndex(s, "]")
		if end > idx {
			s = s[idx+1 : end]
		}
	}

	// Prefix with "." to match deferredFieldIndex keys like ".topologyKey"
	return "." + s
}

// RunStructuralValidation performs reflection-based validation of a runtime.Object
// using pre-compiled structural metadata. It only inspects deferred fields; Phase 1
// (validatePodSpec) already covers non-deferred fields.
func RunStructuralValidation(obj runtime.Object, basePath *field.Path) field.ErrorList {
	if obj == nil {
		return nil
	}

	var errs field.ErrorList
	visitFields(obj, basePath, func(path *field.Path, meta FieldMetadata, fieldVal reflect.Value) {
		// Skip unsupported kinds silently; let k8s decode handle them.
		if meta.Type == "" && meta.EnumValues == nil && meta.MinValue == nil && meta.MaxValue == nil {
			return
		}

		valStr := fieldVal.Interface()
		switch meta.Type {
		case "string":
			if s, ok := valStr.(string); ok {
				if s == "" && meta.Required {
					errs = append(errs, field.Required(path, ""))
					return
				}
				if meta.MinLength != nil && len(s) < *meta.MinLength {
					errs = append(errs, field.Invalid(path, s, fmt.Sprintf("min length is %d", *meta.MinLength)))
					return
				}
				if meta.MaxLength != nil && len(s) > *meta.MaxLength {
					errs = append(errs, field.Invalid(path, s, fmt.Sprintf("max length is %d", *meta.MaxLength)))
					return
				}
				if meta.Format == "string" && s != "" {
					// string format validation passed.
				}
				if len(meta.EnumValues) > 0 {
					found := false
					for _, v := range meta.EnumValues {
						if s == v {
							found = true
							break
						}
					}
					if !found {
						errs = append(errs, field.NotSupported(path, s, meta.EnumValues))
					}
				}
			}
		case "integer", "number":
			if meta.MinValue != nil || meta.MaxValue != nil {
				var num float64
				switch v := valStr.(type) {
				case int64:
					num = float64(v)
				case int32:
					num = float64(v)
				case float64:
					num = v
				default:
					return
				}
				if meta.MinValue != nil && num < *meta.MinValue {
					errs = append(errs, field.Invalid(path, num, ""))
				}
				if meta.MaxValue != nil && num > *meta.MaxValue {
					errs = append(errs, field.Invalid(path, num, ""))
				}
			}
		case "boolean":
			// booleans are optional by default; no-op for now.
		}
	})

	return errs
}

// fieldVisitor is called for each leaf field visited during structural validation.
type fieldVisitor func(path *field.Path, meta FieldMetadata, fieldVal reflect.Value)

// visitFields walks the object graph using reflection and calls visitor for each
// deferred field that has a corresponding entry in the metadata index.
func visitFields(obj runtime.Object, basePath *field.Path, visitor fieldVisitor) {
	if obj == nil {
		return
	}

	// Ensure index is initialized (thread-safe, lazy).
	deferredFieldInit.Do(func() {
		if deferredFieldIndex == nil {
			deferredFieldIndex = make(map[string]FieldMetadata)
		}
	})

	objVal := reflect.ValueOf(obj)
	if objVal.Kind() == reflect.Ptr {
		objVal = objVal.Elem()
	}
	if objVal.Kind() != reflect.Struct {
		return
	}

	// Walk all struct fields recursively.
	walkStruct(objVal, basePath, visitor)
}

// walkStruct recursively walks a struct value and invokes the visitor for each field.
func walkStruct(val reflect.Value, path *field.Path, visitor fieldVisitor) {
	if val.Kind() != reflect.Struct {
		return
	}

	typ := val.Type()
	for i := 0; i < typ.NumField(); i++ {
		sf := typ.Field(i)
		fieldVal := val.Field(i)

		if sf.Anonymous && fieldVal.Kind() == reflect.Struct {
			// Recurse into anonymous embedded structs to follow chains
			// like Volume -> VolumeSource -> AzureFile.
			walkStruct(fieldVal, path, visitor)
			continue
		}

		// Construct the JSON-path-like field path from struct field (lowerCamelCase -> .lowerCamelCase).
		lower := strings.ToLower(sf.Name[:1]) + sf.Name[1:]
		fieldPath := path.Key(lower)

		// Look up in deferred field index using a normalized path (strip array
		// indices so ".topologySpreadConstraints[0].topologyKey" matches ".topologyKey").
		normalized := normalizePath(fieldPath)
		if meta, ok := LookupDeferredField(normalized); ok {
			visitor(fieldPath, meta, fieldVal)
		}

		// Recurse into nested structs and pointers to structs.
		switch fieldVal.Kind() {
		case reflect.Struct:
			walkStruct(fieldVal, fieldPath, visitor)
		case reflect.Ptr:
			if !fieldVal.IsNil() && fieldVal.Elem().Kind() == reflect.Struct {
				walkStruct(fieldVal.Elem(), fieldPath, visitor)
			}
		case reflect.Slice:
			for j := 0; j < fieldVal.Len(); j++ {
				elem := fieldVal.Index(j)
				if elem.Kind() == reflect.Struct {
					walkStruct(elem, fieldPath.Index(j), visitor)
				}
			}
		}
	}
}